project:
  name: growthatpkgs
  nixpkgs_channel: nixos-21.05
  organization: growthatco
  owner: GrowThat Digital Agency, LLC.
  repository: https://github.com/growthatco/growthatpkgs
  version: 1.0.2
stage: development
tools:
  nix: 2.3.14
  nixfmt:
    path: /nix/store/jmf205gcajlva1hh5cfw9pfn1bagv4r7-nixfmt-0.4.0/bin/nixfmt
    version: 0.4.0
  nodejs: 16.4.0
  python: 3.9.4
