arrowParens: "always"
bracketSpacing: true
endOfLine: "lf"
printWidth: 100
proseWrap: "always"
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: true

overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      printWidth: 9999
