name: Release
on:
  push:
    branches:
      - master
      - alpha

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          skip_adding_nixpkgs_channel: true

      # - name: Cachix
      #   uses: cachix/cachix-action@v8
      #   with:
      #     name: gtc-growthatpkgs-rel
      #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Download Nix Dependenices
        run: |
          nix-shell --pure shell.release.nix

  release:
    name: Release
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      # - name: Cachix
      #   uses: cachix/cachix-action@v8
      #   with:
      #     name: gtc-growthatpkgs-rel
      #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install Node.js dependencies
        run: |
          nix-shell --run "npm ci" shell.release.nix

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          nix-shell --run "npm run release" shell.release.nix

  merge:
    name: Merge
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Merge ${{ github.ref }} -> next"
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: next
          github_token: ${{ github.token }}